version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "go/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "java/"
    schedule:
      interval: "weekly"
