name: go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps
      - run: go test
        working-directory: go
        