name: Java CI

on:
    push:
      branches:
        - main
    pull_request:

jobs:
  java-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
    - run:  ./gradlew test
      working-directory: java